name: Run Crypto Script

on:
  schedule:
    - cron: '*/30 2-18 * * *'  # Every 30 min 07:00–22:59 UTC (7:00–10:59 ET) all days
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r crypto/requirements.txt

      - name: Set environment variables
        run: |
          echo "TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}" >> $GITHUB_ENV
          echo "CHAT_ID=${{ secrets.CHAT_ID }}" >> $GITHUB_ENV

      - name: Configure Git for pushing
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git
      
      - name: Push updates
        run: |
          git add models/*.joblib model_metadata.json trade_history.json
          git commit -m "Auto update models and trade history [skip ci]" || echo "No changes to commit"
          git push

      - name: Run script
        run: python crypto/main.py
