name: Run Crypto Script

on:
  schedule:
    - cron: '*/10 * * * *'  # Every 20 min, all days
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r crypto/requirements.txt

      - name: Set environment variables
        run: |
          echo "TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}" >> $GITHUB_ENV
          echo "CHAT_ID=${{ secrets.CHAT_ID }}" >> $GITHUB_ENV

      - name: Run script
        run: python crypto/main.py

      - name: Commit and push model + history files
        if: ${{ github.event_name == 'schedule' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add crypto/models/*.joblib crypto/model_metadata.json crypto/trade_history.json || true
          git commit -m "🔁 Auto update models and trade history [skip ci]" || echo "No changes to commit"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git || echo "Nothing to push"

      - name: List generated files (Debug feature - optional)
        run: |
          ls -R
