name: Run Stock Script

on:
  schedule:
    - cron: '*/20 13-21 * * 1-5'  # Every 20 minutes, 8am-4pm Mon-Fri
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r stock/ind/requirements.txt

      - name: Set environment variables
        run: |
          echo "GITHUB_ACTIONS=true" >> $GITHUB_ENV
          echo "TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}" >> $GITHUB_ENV
          echo "CHAT_ID=${{ secrets.CHAT_ID }}" >> $GITHUB_ENV
          echo "NEWS_API_KEY=${{ secrets.NEWS_API_KEY }}" >> $GITHUB_ENV
          echo "ALPHA_KEY=${{ secrets.ALPHA_KEY }}" >> $GITHUB_ENV

      - name: Run trading script
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python stock/main.py

      - name: Commit and push model, history, and sentiment files
        if: always()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add stock/ind/models/*.joblib stock/ind/model_metadata.json stock/ind/trade_history.json stock/ind/sentiment_cache.pkl || true
          if git status --porcelain | grep .; then
            git commit -m "🔁 Auto update models, trade history, and sentiment cache [skip ci]"
            git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          else
            echo "No changes to commit"
          fi

      - name: List generated files (Debug)
        if: always()
        run: |

          ls -R stock/

